import type { BlogBlock } from "@/app/components/blog/BlogArticle";

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  readingTime: string;
  blocks: BlogBlock[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "compress-pdf-for-application-portals",
    title: "How to Compress PDF Files for Online Application Portals Without Quality Loss",
    description:
      "Many job, visa, and university portals reject PDFs over a strict size limit. Here's how to shrink your file without losing the details that matter.",
    date: "2026-02-10",
    readingTime: "6 min read",
    blocks: [
      {
        type: "p",
        text: "If you've ever tried to upload a resume, a transcript, or a scanned application form to an online portal, you've probably run into the same wall: \"File size exceeds the maximum limit.\" Most application systems cap uploads somewhere between 1 MB and 10 MB, which is tight when a single scanned page from a modern phone camera or flatbed scanner can easily be several megabytes on its own. This guide walks through how to get your PDF under that limit without turning your document into a blurry, unreadable mess.",
      },
      { type: "h2", text: "Why PDFs Get So Large in the First Place" },
      {
        type: "p",
        text: "A PDF's file size is almost never about the text inside it — plain text is tiny. The real weight comes from embedded images: scanned pages, photographed documents, and screenshots. A phone camera can capture a single page at 12 megapixels or more, and when that image gets embedded into a PDF without any compression, the file balloons. Multiply that across a 5-page application packet and you can easily end up with a 20+ MB file for a document that should be a fraction of that size.",
      },
      { type: "h2", text: "Step-by-Step: Compressing a PDF for Portal Upload" },
      {
        type: "ol",
        items: [
          "**Check the portal's actual limit first.** Most application forms state the maximum size near the upload button (commonly 2 MB, 5 MB, or 10 MB). Knowing the target number tells you how aggressive you need to be.",
          "**Run your file through [Compress PDF](/compress-pdf).** Upload your document and let it process — the tool shows you the original size and the new size side by side, so you can see exactly how much was saved before you download anything.",
          "**Compare the before-and-after honestly.** If the reduction isn't enough to clear the portal's limit, the file's size is likely dominated by high-resolution scanned images rather than PDF overhead — in that case, re-scanning at a lower DPI (150–200 DPI is usually plenty for text documents) before compressing again will get you much further than compressing alone.",
        ],
      },
      { type: "h2", text: "What Actually Happens When You Compress a PDF" },
      {
        type: "p",
        text: "It's worth understanding what compression can and can't do, so you're not caught off guard. A PDF is a container format that bundles text, fonts, and images together with a certain amount of internal structural overhead. Efficient compression repackages that structure — sharing repeated objects, removing redundant metadata — to shrink the file without touching how anything looks. This works especially well on multi-page documents, forms with repeated fonts, or PDFs that were generated by older software.",
      },
      {
        type: "p",
        text: "What compression generally can't do — at least not without a separate step — is meaningfully shrink an already highly detailed, high-resolution photograph embedded in the PDF. If your file's size is mostly one giant scanned image, the honest fix is to reduce the *scan resolution* before it ever becomes a PDF, not to squeeze the PDF wrapper afterward.",
      },
      { type: "h2", text: "Tips for Keeping Quality High While Shrinking Size" },
      {
        type: "ul",
        items: [
          "Scan documents in black-and-white or grayscale instead of full color when the content doesn't need color — this alone can cut file size dramatically.",
          "Avoid scanning at unnecessarily high DPI. 150–200 DPI is sharp enough for text-based forms and IDs; 300 DPI+ is really only needed for fine print or small text that needs magnifying.",
          "Crop out blank margins and unused space before converting to PDF — every extra pixel adds weight.",
          "If your source documents are photos rather than scans, convert them with [JPG to PDF](/jpg-to-pdf) using the **Letter** or **A4** page size option, which normalizes the page dimensions rather than embedding an oversized original photo.",
        ],
      },
      { type: "h2", text: "A Quick Pre-Submission Checklist" },
      {
        type: "ul",
        items: [
          "Confirm the exact file size limit stated by the portal.",
          "Compress the PDF and check the resulting size against that limit.",
          "Open the compressed file and visually confirm text is still legible and nothing important got cut off.",
          "If still too large, re-scan source pages at a lower resolution and repeat.",
        ],
      },
      {
        type: "p",
        text: "Getting a document portal-ready doesn't have to mean sacrificing legibility. With a realistic understanding of where PDF size actually comes from, a couple of minutes of prep work is usually all it takes to get comfortably under any upload limit.",
      },
    ],
  },
  {
    slug: "combine-scanned-receipts-into-one-pdf",
    title: "How to Combine Multiple Scanned Receipts and Documents into One PDF",
    description:
      "Expense reports, tax filing, and reimbursement forms almost always want one PDF, not a folder of loose images. Here's the fastest way to get there.",
    date: "2026-02-24",
    readingTime: "5 min read",
    blocks: [
      {
        type: "p",
        text: "Anyone who has filed an expense report knows the drill: a pile of paper receipts, a phone full of photos taken at odd angles, and a finance portal that only accepts a single PDF attachment. Doing this manually — importing each photo into a document editor, arranging pages, exporting — takes far longer than it should for something this routine. This guide covers a faster path from \"folder full of receipt photos\" to \"one clean PDF, ready to submit.\"",
      },
      { type: "h2", text: "Why Reviewers Prefer One PDF Over Several Images" },
      {
        type: "p",
        text: "Most expense, tax, and reimbursement systems are built around document review, not photo galleries. A single, page-ordered PDF lets a reviewer open one file and scroll through everything in sequence, rather than downloading five separate JPGs and guessing which receipt belongs to which line item. It also just looks more organized — which matters when the person approving your report has a stack of dozens of these to get through.",
      },
      { type: "h2", text: "The Two-Step Process" },
      { type: "h3", text: "Step 1: Turn your receipt photos into a PDF" },
      {
        type: "p",
        text: "If your receipts exist as photos (JPG or PNG) on your phone or computer, start with [JPG to PDF](/jpg-to-pdf). Select all of the receipt images at once — the tool lets you reorder them before converting, so you can arrange them chronologically or by category before you ever generate the file. Choosing the **Auto** page size keeps each page sized to match its photo, which avoids the odd white borders you'd get from forcing a receipt photo onto a full A4 or Letter page.",
      },
      { type: "h3", text: "Step 2: Merge in any existing PDF receipts or invoices" },
      {
        type: "p",
        text: "If some of your receipts already exist as PDFs — email invoices, downloaded order confirmations, or hotel folios — you don't need to convert those to images first. Use [Merge PDF](/merge-pdf) to combine your newly converted receipt PDF with any existing PDF receipts into a single document. The file list lets you reorder everything before merging, so the final document reads in a logical order from top to bottom.",
      },
      { type: "h2", text: "Tips for a Cleaner Result" },
      {
        type: "ul",
        items: [
          "**Photograph receipts flat and well-lit.** A receipt photographed at an angle or in dim light is harder to read once it's in the final PDF — a few extra seconds when taking the photo saves rework later.",
          "**Name your files before uploading them**, like `01-taxi.jpg`, `02-hotel.jpg`, so they're easy to select in the right order.",
          "**Keep the total file size in mind.** If you're combining a large number of high-resolution photos, the resulting PDF can get large quickly — running it through [Compress PDF](/compress-pdf) afterward can bring it back under a portal's upload limit without a separate export step.",
          "**Double-check the page order** in the final file before submitting — it's much faster to catch a misordered receipt before submission than to explain a confusing expense report afterward.",
        ],
      },
      { type: "h2", text: "What About Faded or Hard-to-Read Receipts?" },
      {
        type: "p",
        text: "Thermal-paper receipts fade fast, sometimes within weeks. If a receipt is already hard to read, photographing it sooner rather than later — and increasing brightness slightly when photographing — gives you a better source image to work with. No PDF tool can recover detail that was never captured, so the biggest quality factor is always the original photo, not the conversion step.",
      },
      { type: "h2", text: "Building a Repeatable Habit for Frequent Travelers" },
      {
        type: "p",
        text: "If expense reports are a recurring part of your work, it's worth turning this into a habit rather than a once-a-month scramble. Photograph each receipt the same day you get it, save it into a dedicated folder for the current trip or reporting period, and give it a short descriptive filename right away while the context is still fresh in your memory. When it's time to submit, you'll already have a clean, ordered set of images ready to convert and merge in a couple of minutes, instead of trying to reconstruct which crumpled receipt belonged to which meal three weeks later.",
      },
      {
        type: "p",
        text: "Once you're in the habit of converting-then-merging, turning a shoebox of receipts into one submission-ready PDF becomes a two or three minute task instead of a recurring headache at the end of every trip or expense cycle.",
      },
    ],
  },
  {
    slug: "pdf-vs-jpg-which-format-to-use",
    title: "PDF vs. JPG: Which Format Should You Use for Documents and Images?",
    description:
      "PDF and JPG solve different problems. Here's a practical breakdown of when each format actually makes sense, and how to convert between them when you guessed wrong.",
    date: "2026-03-03",
    readingTime: "6 min read",
    blocks: [
      {
        type: "p",
        text: "PDF and JPG show up constantly in everyday digital life, but they're built for genuinely different jobs. Using the wrong one is a common source of friction — a JPG that won't print correctly across multiple pages, or a PDF that's needlessly large for what's really just a single photo. This guide breaks down what each format is actually good at, so you can pick correctly the first time.",
      },
      { type: "h2", text: "What JPG Is Built For" },
      {
        type: "p",
        text: "JPG (or JPEG) is an image compression format, full stop. It's designed to represent a single photograph efficiently — think camera photos, screenshots, or web graphics — by compressing pixel data in a way that trades a small amount of visual detail for a much smaller file size. JPG has no concept of \"pages,\" text layout, or fonts. It's just a picture.",
      },
      {
        type: "ul",
        items: [
          "**Use JPG when:** you're sharing a photo, posting an image online, or storing a single picture where file size matters more than perfect pixel accuracy.",
          "**Avoid JPG when:** you need to preserve sharp text, combine multiple pages, or send something that should print consistently regardless of the device or app used to open it.",
        ],
      },
      { type: "h2", text: "What PDF Is Built For" },
      {
        type: "p",
        text: "PDF (Portable Document Format) was designed to solve a very different problem: making a document look identical no matter what device, operating system, or software opens it. A PDF can contain multiple pages, embedded fonts, vector text that stays sharp at any zoom level, and a mix of text and images — all in one file that renders the same way everywhere.",
      },
      {
        type: "ul",
        items: [
          "**Use PDF when:** you're sending a multi-page document, a form, a resume, an invoice, or anything where consistent formatting and print-readiness matter.",
          "**Avoid PDF when:** the content really is just a single photo with no text or layout — converting a simple photo to PDF often just adds file overhead for no benefit.",
        ],
      },
      { type: "h2", text: "The Quality Difference Explained Simply" },
      {
        type: "p",
        text: "Text inside a genuine PDF (not a scanned image of text) is rendered from vector font data, so it stays perfectly crisp at any zoom level and remains selectable and searchable. Text inside a JPG is just a grid of colored pixels — zoom in far enough and it visibly blurs, and there is no way to select or search it. This is the core reason application forms, contracts, and official documents are almost always expected as PDFs rather than photos.",
      },
      { type: "h2", text: "Converting Between the Two" },
      { type: "h3", text: "Turning a PDF into JPG images" },
      {
        type: "p",
        text: "Sometimes you need the opposite of a document — for example, dropping a page from a PDF into a slide deck or a website where only image formats are accepted. [PDF to JPG](/pdf-to-jpg) renders each page of a PDF as a standalone JPG image, so a multi-page document becomes a set of individual pictures you can drop anywhere an image is expected.",
      },
      { type: "h3", text: "Turning photos into a proper PDF" },
      {
        type: "p",
        text: "If you have several photographed pages — a signed contract, a form filled out by hand, receipts, or ID pages — that need to become one properly formatted document, [JPG to PDF](/jpg-to-pdf) combines them into a single multi-page PDF with a consistent page size, rather than leaving them as a scattered set of loose images.",
      },
      { type: "h2", text: "Quick Decision Guide" },
      {
        type: "ul",
        items: [
          "Sharing a single photo casually → **JPG**",
          "Submitting a form, resume, or official document → **PDF**",
          "Need a page from a PDF to use as an image → convert with **PDF to JPG**",
          "Have photographed pages that need to be one document → convert with **JPG to PDF**",
        ],
      },
      {
        type: "p",
        text: "Neither format is objectively \"better\" — they're built for different jobs. Once you know which job you're actually doing, picking the right one (or converting to it) takes seconds.",
      },
    ],
  },
  {
    slug: "browser-based-pdf-processing-vs-cloud-converters",
    title: "Why Browser-Based Local PDF Processing Is Safer Than Cloud Converters",
    description:
      "Many free PDF tools quietly upload your files to a server before processing them. Here's what that actually means for your privacy, and how to tell the difference.",
    date: "2026-03-17",
    readingTime: "6 min read",
    blocks: [
      {
        type: "p",
        text: "When you search for a free way to merge, split, or compress a PDF, most of the results work the same way behind the scenes: you upload your file to a server, a program on that server processes it, and you download the result. That model has been the default for years — but it also means a copy of whatever you uploaded, whether it's a resume, a contract, a medical form, or a tax document, briefly (or not so briefly) exists on a computer you don't control.",
      },
      { type: "h2", text: "How Server-Based PDF Tools Actually Work" },
      {
        type: "p",
        text: "When a website processes your PDF \"in the cloud,\" your browser sends the entire file over the internet to that company's servers. The server runs the merge, split, or compression logic, generates a result, and sends it back. Somewhere in that process, your original file exists on hardware operated by a third party — and what happens to it after that depends entirely on that company's internal practices, retention policies, and security posture, none of which you can directly verify.",
      },
      {
        type: "ul",
        items: [
          "Even with a stated \"we delete files after 1 hour\" policy, you're trusting that policy is actually implemented and enforced correctly.",
          "A server breach, misconfigured storage bucket, or internal access control mistake could expose uploaded files — this has happened to file-processing services before.",
          "Uploading is inherently slower than local processing, since your file has to travel to a server and back before you see a result.",
        ],
      },
      { type: "h2", text: "How Browser-Based (Client-Side) Processing Is Different" },
      {
        type: "p",
        text: "Client-side processing takes a fundamentally different approach: instead of sending your file to a server, the merging, splitting, or converting logic runs as JavaScript directly inside your own browser, on your own device. Your file is read from your disk into your browser's memory, transformed there, and the result is handed back to you as a download — without ever being transmitted anywhere.",
      },
      {
        type: "p",
        text: "On Foldryn, this is how [Merge PDF](/merge-pdf), [Split PDF](/split-pdf), [Compress PDF](/compress-pdf), [PDF to JPG](/pdf-to-jpg), and [JPG to PDF](/jpg-to-pdf) all work — the actual processing happens with libraries running in your browser tab, not on a remote server. There is no upload step for these tools to skip, because the architecture never sends your file out in the first place.",
      },
      { type: "h2", text: "Why This Matters More for Some Documents Than Others" },
      {
        type: "p",
        text: "Not every PDF is sensitive — a public flyer or a template probably doesn't need special handling. But a huge share of everyday PDF tasks involve documents that are genuinely private: signed contracts, financial statements, medical records, ID scans, and tax paperwork. For exactly those documents, avoiding an unnecessary upload to a third-party server is a meaningful, practical reduction in exposure — there's simply one less place the file could end up.",
      },
      { type: "h2", text: "How to Tell If a Tool Is Actually Processing Locally" },
      {
        type: "ul",
        items: [
          "**Check the network activity.** In most browsers, you can open developer tools and watch the Network tab while running a tool — if no request containing your file leaves your device, it's processing locally.",
          "**Read the tool's own privacy claims carefully.** A trustworthy client-side tool will say so plainly and specifically, rather than making vague \"we care about your privacy\" statements without explaining the actual architecture.",
          "**Try it with your internet briefly disabled.** A genuinely browser-based tool that has already loaded will often still work, since it doesn't need a server round-trip to function.",
        ],
      },
      {
        type: "p",
        text: "Browser-based processing isn't a marketing buzzword — it's a specific architectural choice that removes an entire category of risk by never creating an unnecessary copy of your file in the first place. When you're deciding which PDF tool to trust with a sensitive document, it's worth knowing which kind you're actually using.",
      },
    ],
  },
  {
    slug: "how-to-split-extract-pages-from-pdf",
    title: "How to Split and Extract Specific Pages From Large PDF Documents",
    description:
      "Whether you need one page out of a hundred-page report or want to break a document into individual files, here's how to do it cleanly.",
    date: "2026-03-31",
    readingTime: "5 min read",
    blocks: [
      {
        type: "p",
        text: "Large PDFs are common — a full contract packet, a scanned book chapter, a government form bundle, or a lengthy report — but you rarely need the whole thing. More often, you need one section, a handful of specific pages, or want to break the file apart entirely so each page stands on its own. Doing this without the right tool usually means scrolling through a bloated PDF viewer or, worse, manually screenshotting pages. Here's a cleaner way to do it.",
      },
      { type: "h2", text: "Two Different Problems, Two Different Approaches" },
      {
        type: "p",
        text: "\"Splitting a PDF\" actually covers two distinct needs, and it helps to know which one you have before you start:",
      },
      {
        type: "ul",
        items: [
          "**Extracting specific pages** — you want pages 1, 3, and 5 through 8 out of a longer document, combined into one new, shorter PDF.",
          "**Splitting every page apart** — you want each individual page of the document saved as its own separate PDF file.",
        ],
      },
      { type: "h2", text: "How to Extract Specific Pages" },
      {
        type: "p",
        text: "Use [Split PDF](/split-pdf) and choose the **Extract pages** option. You'll be asked for a page range, using a simple format like `1,3,5-8` — meaning pages 1, 3, 5, 6, 7, and 8. Those pages are pulled out and combined into a single new PDF, in the order you specified, while everything else in the original document is left out.",
      },
      {
        type: "ol",
        items: [
          "Upload your PDF and note the total page count shown by the tool.",
          "Choose **Extract pages** and enter the pages or ranges you need.",
          "Process the file, then use the Download button to save your new, shorter PDF.",
        ],
      },
      { type: "h3", text: "A practical example" },
      {
        type: "p",
        text: "Say you have a 40-page lease agreement, but your accountant only needs the signature page and the payment schedule — pages 1, 38, and 39. Entering `1,38,39` extracts exactly those three pages into one small PDF, instead of sending the entire 40-page document for three pages of relevant content.",
      },
      { type: "h2", text: "How to Split Every Page Into Its Own File" },
      {
        type: "p",
        text: "If instead you need each page as a completely separate file — for example, uploading each page of a multi-page form to different fields in a system — choose **Split every page** instead. The tool breaks the document into one PDF per page. If there's more than one resulting file, they're automatically bundled into a single ZIP archive so you can download everything at once rather than one file at a time.",
      },
      { type: "h2", text: "Tips for Working With Large Documents" },
      {
        type: "ul",
        items: [
          "**Note the page numbers before you start.** Open the PDF once in a normal viewer to confirm exactly which page numbers you need — page numbers printed inside the document don't always match the PDF's actual page order.",
          "**Double-check ranges for typos.** A range like `5-8` extracts pages 5 through 8 inclusive; a stray comma or dash in the wrong place will throw a validation error rather than silently doing the wrong thing, so re-check if you see one.",
          "**Recombine later if needed.** If you extract pages from several different documents and want them in one final file, [Merge PDF](/merge-pdf) can combine the resulting PDFs back into a single document, in whatever order you choose.",
          "**Watch the file size on very large source PDFs.** Extremely long documents (hundreds of pages, or large embedded images) rely on your browser's available memory to process, so extracting a smaller subset of pages is generally faster and more reliable than processing an enormous file for a large split.",
        ],
      },
      {
        type: "p",
        text: "Splitting a PDF the right way comes down to picking the correct mode for what you actually need — a smaller extracted document, or a full set of individual pages — and getting your page numbers right before you run it. Once you know the difference, it's a task that takes seconds rather than minutes of manual scrolling and screenshotting.",
      },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}
